name: Build

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  actions: read
  contents: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install system dependencies
        run: |
          sudo apt-get install -y binutils rustc cargo pkg-config libssl-dev
      - name: Build Deb
        run: |
          ./build-deb.sh
